title: DNA Dynamite
description: "Illumina DNA Dynamite Game"
owner_name: Team Smart Cells
github_username: blackstar3092
github_repo: "illumina_pc_frontend" 
baseurl: "/illumina_pc_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/gamerules.md
  - navigation/predict.md
  - navigation/search.md
